name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
    steps:
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt-get install make cmake autoconf automake pkg-config 
        shell: bash
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Run CAKE
        run: dotnet cake
      - name: Package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Native-${{ matrix.os }}
          path: |
            artifacts/*
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ build ]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Install .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download artifacts for Windows x64
        uses: actions/download-artifact@v3
        with:
          name: Native-windows-latest
          path: src/JoltPhysicsSharp/runtimes
      - name: Download artifacts for macOS
        uses: actions/download-artifact@v3
        with:
          name: Native-macos-latest
          path: src/JoltPhysicsSharp/runtimes/osx-universal/native
      - name: Download artifacts for Linux x64
        uses: actions/download-artifact@v3
        with:
          name: Native-ubuntu-20.04
          path: src/JoltPhysicsSharp/runtimes/linux-x64/native
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Run CAKE
        run: dotnet cake --target Package
      - uses: actions/upload-artifact@v3
        with:
          name: nuget_release
          path: |
            ./artifacts/*
          if-no-files-found: error
      - name: Publish to NuGet
        if: github.event_name == 'push'
        run: dotnet nuget push artifacts/**/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate --source https://api.nuget.org/v3/index.json          
